### PR TITLE
Improve element parsing

### LINKED ISSUE #6: Should support tag names with hyphens

### PR DESCRIPTION
**Pull request by rowanseymour**
* Adds support for classes being before ids (fixes https://github.com/jessemiller/HamlPy/issues/126)
* Adds support for tags with hyphens (fixes #6)
* `Element` class now stores unrendered state and `render_attributes` does rendering of HTML attributes when required. This makes it easier to test.

### CODE REVIEW

**Comment by rowanseymour** [comment]
@Psycojoker please review when you get a chance

**Comment by rowanseymour** [comment]
@Psycojoker sorry to pester but really want to get this merged this week if possible

**Comment by Psycojoker** [comment]
@rowanseymour gonna try to look at this this evening, sorry I'm really busy right now :/

**Comment by Psycojoker** [comment]
Sorry, took me a bit of time to fully review your changes. They do improve code readability, thanks for that :)

**Comment by Psycojoker** [comment]
Tell me if you feel confident enough for a release.

**Comment by rowanseymour** [comment]
Yes please make one

**Comment by Psycojoker** [comment]
https://pypi.python.org/pypi/django-hamlpy/0.86

**Pull request merged**
