### PR TITLE
Update README with info on how to fix linux install error

### PR DESCRIPTION
**Pull request by Kangaroux**

### CODE REVIEW

**Comment by rowanseymour** [comment]
I'm not convinced we need this as it's a general Python 3 issue rather than anything specific to this project. Maybe we can reduce it to a single line just reminding devs that they'll need to install the Python3 dev package in their environment.

**Comment by Kangaroux** [comment]
@rowanseymour How about:

[Install notes...]
If you are using Linux, you may need to install [python's development package](http://stackoverflow.com/a/21530768/2896976) prior to install if you are encountering build errors.

**Comment by Psycojoker** [comment]
Ah, that's a very standard pip error, I think that you can simply had a section "if you are using linux, you need to install python headers, you can do this on debian/ubuntu by doing

    sudo apt-get install python-dev
    # or for python3
    sudo apt-get install python3-dev

Or for yum-based distribution ..."

**Comment by Kangaroux** [comment]
Updated copy

**Comment by Psycojoker** [comment]
Thanks :)

**Pull request merged**
