### PR TITLE
Make ={...} syntax support optional

### PR DESCRIPTION
**Pull request by rowanseymour**
This PR punts on the question of deprecating `={...}` for now, and just makes it optional using the `HAMLPY_DJANGO_INLINE_STYLE` setting.

I still think deprecation is the way to go, especially once we add support for `.(attr=val)` syntax which introduces yet another meaning for `=`. I just want more time to think through the path to becoming more HAML and less HAMLPY. It bothers me that we'll be supporting three different syntaxes for attributes (`.{attr:val}`, `.{attr=>val}` and `.(attr=val)`) but dropping support for syntax that people are using is always tricky.

Addresses #16. @Psycojoker please review

### CODE REVIEW

**Comment by Psycojoker** [comment]
It would be great to find a way to throw a depreciation warning if we find that the old syntax is still used instead of disabling it by default and breaking on a "pip -U".

I don't know if it's a lot of work :/

**Comment by rowanseymour** [comment]
@Psycojoker agreed but this PR doesn't disable it by default - this PR is completely backwards compatible

**Comment by Psycojoker** [comment]
Oh, my bad, shouldn't review tired after work, sorry :/

**Comment by rowanseymour** [comment]
Np. Did you actually get a chance to look at the code? Would really love to get this merged as we need this to use the latest django-hamlpy with our main project.

**Comment by rowanseymour** [comment]
@Psycojoker bump. I don't like to pester but this PR has been open almost two weeks and we need it

**Pull request merged**
